version: '3.8'

services:
  webhook-tester:
    build: .
    container_name: webhook-tester
    ports:
      - "80:3000"  # Map external port 80 to internal port 3000
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      # Optional: Mount a volume for logs if needed
      - webhook-logs:/app/logs
    networks:
      - webhook-network

  # Optional: Add a simple web interface or monitoring
  # You can extend this with additional services like nginx proxy, etc.

volumes:
  webhook-logs:

networks:
  webhook-network:
    driver: bridge